var translationsAR = {
    'Home' : 'الرئيسية', 
    'Discover' : 'تعرف', 
    'Chat' : 'الدردشة', 
    'Likes' :'المفضلة', 
    'Search' : 'البحث',
    'Meet New Prople':'مقابلة ناس جدد' ,
    'Amazing Features':'مميزات رائعة',
    'Success Stories':'قصص نجاح',
    'Premium Membership':'اعضاء مميزين',
    'Latest Registered Members':'أحدث الأعضاء المسجلين', 
    'Find your life partner':"ابحث عن شريك حياتك",
    'START NOW FOR':"ابدا الان",
    "FREE":"مجانا",
    "DAY TRIAL":"ايام تجريبية",
    "Sign In":"تسجيل دخول",
    "Sign Up":"حساب جديد",
    "welcome":"مرحبا",
    "Notification":"الاشعارات",
    "Upgrade":"تحديث",
    "Profile":"الملف الشخصي",
    "Edit Profile":"تعديل البيانات الشخصية",
    "Change Password":"تعديل كلمة المرور",
    "LogOut":"تسجيل الخروج",
    "Get a membership":"احصل على عضوية",
    "Man":"رجل",
    "Men":"رجال",
    "Woman":"امراة",
    "Women":"نساء",
    "Age":"العمر",
    "country":"الدولة",
    'Join Now':"انضم الان",
    "Read More":"قراءة المزيد",
    "Seeking a":"ابحث عن",
    "View Options":"عرض الخيارات",
    "Free 7 Days":" ايام مجانا 7",
    "Suggestions":"المقترحات ",
    "Search Suggestions":"اقتراحات البحث",
    "Advance Filter":"بحث متقدم",
    "Name":"الاسم",
    "Education":"التعليم ",
    "Search By":"البحث بواسطة ",
    "Total Members":"العدد الكلي",
    "Members Online":"المتاح حاليا",
    "Online":"متاحين حاليا",
    "The password and confirmed are not equal":"كلمة المرور وتاكيدها غير متطابقا",
    "Save":"حفظ",
    "Login":"دخول",
    "Email":"البريد الالكتروني",
    "Password":"كلمة المرور",
    "Remember Password":"تذكر كلمة المرور",
    "Forget Password":"نسيت كلمة المرور",
    "Or":"أو",
    "User Name":"اسم المستخدم",
    "Confirm password":"تأكيد كلمة المرور",
    "Terms & Conditions":"الاحكام والقيود",
    "Next":"التالي",
    "Years Old" : "سنوات",
    "Looking For":"ابحث عن",
    "Religion":"الديانة",
    "Hobbies":"المواهب",
    "For More Features":"لمزيد من الميزات",
    "Got It":"احصل عليها",
    "from":"من",
    "to":"الى",
    "Select":"اختر",
    "Likes":"المفضلة",
    "Resume":"السيرة الذاتية",
    "Gallery" :"الالبوم",
    "Information":"المعلومات الشخصية",
    "Gender" :"الجنس",
    "Social Links" :"روابط  مواقع التواصل الاجتماعي",
    "Determination":"حول",
    "Old Password":"كلمة المرور القديمة",
    "New Password":"كلمة المرور الجديدة",
    "Reset Password":"إعادة تعيين كلمة المرور",
    "Enter":"ادخل",
    "Reset":"إعادة التعيين",
    "Sent":"إرسال",
    "Forgot Your Password":"هل نسيت كلمة المرور ",
    "Enter the email associated with your account":"أدخل البريد الإلكتروني الخاص بحسابك",
    "You have Acount":"هل لديك حساب؟",
    "Login Please":"سجل دخول من فضلك",
    "With just a few clicks you will be ready to start your love adventure":"من خلال بضع نقرات فقط ، ستكون جاهزًا لبدء مغامرة الحب",
    "Birth Date":"تاريخ الميلاد",
    "Phone Number":"رقم الهاتف",
    "Male":"ذكر",
    "Female":"أنثى",
    "Enter your education here":"ادخل تخصصك",
    "Female":"أنثى",
    "More":"المزيد",
    "Profile Photo":"الصورة الشخصية",
    "Profile Cover":"صورة الغلاف",
    "Finish":"تسجيل",
    "My Profile":"الملف الشخصي",
    "Forgot Password":"نسيت كلمة المرور",
    "Reset Password":"تعديل كلمة المرور",
    "Edit Profile":"تعديل بياناتي",
    "year Old":"سنة",
    'error_activation' : 'عذراً، حسابك معطل من قبل الادارة.',
    'Tell us who you are!':"أخبرنا من انت!",
    'Find the right person':'ابحث عن الشخص المناسب',
    'Start Dating':"ابدأ بالمواعدة",
    'View More':"عرض المزيد",
    'Quick Search':"البحث السريع",
    'You May Like':"قد يعجبك",
    'Same Hobbies':"نفس المواهب",
    "Get to know":"بدأ يتعرف",
    'Recently Joined':"المنضمون حديثا",
    "Suitable For You":"المناسب لك",
    "you must accept terms and conditions":"يجب عليك قبول الشروط والأحكام",
    "Previous":"السابق",
    "suggests"  :"المقترحات"  ,
    "user_hobbies":"نفس المواهب",
    "user_Interests":"قد يعجبك",
    "new_registers":"المنضمون حديثا",
    "Change":"تغيير ",
    "Login Please":"سجل دخول من فضلك",
    "General Informations":"معلومات عامة",
    "Album":"الالبوم",
    "Date Of Birth":"تاريخ الميلاد",
    "Add Images":"اضافة صور",
    "Write Message ...":"اكتب رسالة ...",
    "Chats":"الدردشات",
    "Subscribe":"اشترك الان",
    "Save Successfully":"تم الحفظ بنجاح",
    
}; 
