var translationsEN = {
    'Home' : 'Home', 
    'Discover' : 'Discover', 
    'Chat' : 'Chat', 
    'Likes' :'Likes', 
    'Search' : 'Search',
    'Meet New Prople':'Meet New Prople' ,
    'Amazing Features':'Amazing Features',
    'Success Stories':'Success Stories',
    'Premium Membership':'Premium Membership',
    'Latest Registered Members':'Latest Registered Members',
    'Find your life partner':"Find your life partner",
    'START NOW FOR':"START NOW FOR",
    "FREE":"FREE",
    "DAY TRIAL":"DAY TRIAL",
    "Sign In":"Sign In",
    "Sign Up":"Sign Up",
    "welcome":"welcome",
    "Notification":"Notification",
    "Upgrade":"Upgrade",
    "Profile":"Profile",
    "Edit Profile":"Edit Profile",
    "Change Password":"Change Password",
    "LogOut":"LogOut",
    "Get a membership":"Get a memberships",
    "Man":"Man",
    "Men":"Men",
    "Woman":"Woman",
    "Women":"Women",
    "Age":"Age",
    'Join Now':"Join Now",
    "Read More":"Read More",
    "Seeking a":"Seeking a",
    "View Options":"View Options",
    "Free 7 Days":"Free 7 Days",
    "Suggestions":"Suggestions ",
    "Search Suggestions":"Search Suggestions",
    "Advance Filter":"Advance Filter",
    "Name":"Name",
    "Education":"Education ",
    "Search By":"Search By",
    "Total Members":"Total Members",
    "Members Online":"Members Online",
    "Online":"Online",
    "The password and confirmed are not equal":"The password and confirmed are not equal",
    "You have Acount":"You have Acount?",
    "Save":"Save",
    "Login":"Login",
    "Email":"Email",
    "Password":"Password",
    "Remember Password":"Remember Password",
    "Forget Password":"Forget Password",
    "Or":"Or",
    "User Name":"User Name",
    "Confirm password":"Confirm password",
    "Terms & Conditions":"Terms & Conditions",
    "Next":"Next",
    "Years Old" : "Years Old",
    "Looking For":"Looking For",
    "Religion":"Religion",
    "Hobbies":"Hobbies",
    "For More Features":"For More Features",
    "Got It":"Got It",
    "from":"from",
    "to":"to",
    "Select":"Select",
    "Likes":"Likes",
    "Resume":"Resume",
    "Gallery" :"Gallery",
    "Information":"Information",
    "Gender" :"Gender",
    "Social Links" :"Social Links",
    "Determination":"Determination",
    "Old Password":"Old Password",
    "New Password":"New Password",
    "Reset Password":"Reset Password",
    "Enter":"Enter",
    "Reset":"Reset",
    "Sent":"Sent",
    "Forgot Your Password":"Forgot Your Password",
    "Enter the email associated with your account":"Enter the email associated with your account",
    "Login Please":"Login Please",
    "With just a few clicks you will be ready to start your love adventure":"من خلال بضع نقرات فقط ، ستكون جاهزًا لبدء مغامرة الحب",
    "Birth Date":"Birth Date",
    "Phone Number":"Phone Number",
    "Male":"Male",
    "Enter your education here":"Enter your education here",
    "Female":"Female",
    "More":"More",
    "Profile Photo":"Profile Photo",
    "Profile Cover":"Profile Cover",
    "Finish":"Finish",
    "My Profile":"My Profile",
    "Forgot Password":"Forgot Password",
    "year Old":"year Old",
    'Tell us who you are!':"Tell us who you are!",
    'Find the right person':'Find the right person',
    'Start Dating':"Start Dating",
    'View More':"View More",
    'Quick Search':"Quick Search",
    'You May Like':"You May Like",
    'Same Hobbies':"Same Hobbies",
    "Get to know":"Get to know",
    'Recently Joined':"Recently Joined",
    "Suitable For You":"Suitable For You",
    "you must accept terms and conditions":"you must accept terms and conditions",
    "Previous":"Previous",
    "Change":"Change ",
    "Album":"Album",
    "country":"Country",
    'error_activation': 'Sorry, your account has been deactivated by the admin.',
    "suggests"  :"Suggestions"  ,
    "user_hobbies":"Same Hobbies",
    "user_Interests":"You May Like",
    "new_registers":"Recently Joined",
    "General Informations":"General Information's",
    "Date Of Birth":"Date Of Birth",
    "Add Images":"Add Images",
    "Write Message ...":"Write Message ...",
    "Chats":"Chats",
    "Subscribe":"Subscribe",
    "Save Successfully":"Save Successfully",
}; 
