var translationsES = {
    'Home' : 'Home', 
    'Discover' : 'Discover', 
    'Chat' : 'Chat', 
    'Likes' :'Likes', 
    'Search' : 'Search', 
    'Meet New Prople':'Meet New Prople' ,
    'Amazing Features':'Amazing Features',
    'Success Stories':'Success Stories',
    'Premium Membership':'Premium Membership',
    'Latest Registered Members':'Latest Registered Members',
    'Find your life partner':"Find your life partner",
    'START NOW FOR':"START NOW FOR",
    "free":"free",
    "DAY TRIAL":"DAY TRIAL",
    "The password and confirmed are not equal":"The password and confirmed are not equal",
    'error_activation' : 'Lo sentimos, su cuenta ha sido desactivada por el administrador.',
    "suggests"  :"Suggestions"  ,
    "user_hobbies":"Same Hobbies",
    "user_Interests":"You May Like",
    "new_registers":"Recently Joined",
}; 
